---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: prajwalpadal/tutorial-app-api:v2.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysqldb-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysqldb-secret
                  key: MYSQLDB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqldb-secret
                  key: MYSQLDB_ROOT_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysqldb-config
                  key: MYSQLDB_DATABASE
            - name: DB_PORT
              value: "3306"
            - name: CLIENT_ORIGIN
              value: "*"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: api
