---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqldb-config
  namespace: default
  labels:
    app: mysqldb
data:
  MYSQLDB_DATABASE: bezkoder_db
  DB_HOST: mysqldb
---
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-secret
  namespace: default
  labels:
    app: mysqldb
type: Opaque
data:
  MYSQLDB_USER: cm9vdA==
  MYSQLDB_ROOT_PASSWORD: MTIzNDU2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: default
data:
  REACT_APP_API_BASE_URL: http://api:8080/api
