apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  type: LoadBalancer
  ports:
    - name: "frontend-port"
      protocol: TCP
      port: 5173
      targetPort: 5173
  selector:
    app: frontend
